package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/Zachacious/go-respec/internal/analyzer"
	"github.com/Zachacious/go-respec/internal/assembler"
	"github.com/Zachacious/go-respec/internal/config"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

// These variables are set at build time by the Makefile's ldflags
var (
	version = "dev"
	commit  = "none"
	date    = "unknown"
)

// defaultRespecYAML contains the content for the default .respec.yaml file.
const defaultRespecYAML = `# .respec.yaml - Configuration for the respec OpenAPI generator

# High-level information for your OpenAPI specification.
info:
  title: "Untitled API"
  version: "1.0.0"
  description: "A new API generated by respec."

# Defines the security mechanisms your API uses (e.g., JWT, API Keys).
securitySchemes:
  BearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT

# Teaches respec the routing syntax of your web framework.
# Defaults for chi/v5 and gin-gonic/gin are built-in.
# Only uncomment and modify this section if you use a different framework.
# routerDefinitions:
#   - type: "github.com/go-chi/chi/v5.Mux"
#     endpointMethods: ["Get", "Post", "Put", "Patch", "Delete", "Head", "Options", "Trace"]
#     groupMethods: ["Route", "Group"]
#     middlewareWrapperMethods: ["With", "Use"]

# Teaches respec to infer details from your project's custom helper functions.
# Defaults for the standard library and common frameworks are built-in.
# handlerPatterns:
#   requestBody:
#     - functionPath: "path/to/my/utils.BindRequest"
#       argIndex: 0
#   responseBody:
#     - functionPath: "path/to/my/utils.RespondWithJSON"
#       statusCodeIndex: 1
#       dataIndex: 2
#       descriptionIndex: -1 # Use -1 if no description argument

# Maps function calls found in middleware to the security schemes defined above.
# securityPatterns:
#   - functionPath: "path/to/my/auth.ValidateToken"
#     schemeName: "BearerAuth"
`

func main() {
	var outputPath string

	// rootCmd is the main command for generating the spec.
	var rootCmd = &cobra.Command{
		Use:   "respec [path]",
		Short: "respec is a Go static analysis tool to generate OpenAPI specs without magic comments.",
		Long: `respec analyzes a Go project's source code to infer API routes, handlers,
and schemas, producing a valid OpenAPI v3 specification. It is designed to be
framework-agnostic and highly configurable through a .respec.yaml file.`,
		Args: cobra.MaximumNArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			projectPath := "."
			if len(args) > 0 {
				projectPath = args[0]
			}

			fmt.Printf("Starting analysis of project at: %s\n", projectPath)
			cfg, err := config.Load(projectPath)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Error loading .respec.yaml: %v\n", err)
				os.Exit(1)
			}
			fmt.Println("Configuration loaded.")

			apiModel, err := analyzer.Analyze(projectPath, cfg)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Error during analysis: %v\n", err)
				os.Exit(1)
			}
			fmt.Println("Analysis complete. Assembling specification...")

			spec, err := assembler.BuildSpec(apiModel, cfg)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Error assembling specification: %v\n", err)
				os.Exit(1)
			}

			var outputData []byte
			// Check the output file extension to determine the format.
			if strings.HasSuffix(strings.ToLower(outputPath), ".json") {
				fmt.Println("Marshalling spec to JSON...")
				outputData, err = json.MarshalIndent(spec, "", "  ")
			} else {
				fmt.Println("Marshalling spec to YAML...")
				outputData, err = yaml.Marshal(spec)
			}

			if err != nil {
				fmt.Fprintf(os.Stderr, "Error marshalling spec: %v\n", err)
				os.Exit(1)
			}

			err = os.WriteFile(outputPath, outputData, 0644)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Error writing output file: %v\n", err)
				os.Exit(1)
			}
			fmt.Printf("Successfully generated OpenAPI spec at: %s\n", outputPath)
		},
	}

	// versionCmd prints the version information.
	var versionCmd = &cobra.Command{
		Use:   "version",
		Short: "Print the version number of respec",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Printf("respec version %s\n", version)
			fmt.Printf("commit: %s\n", commit)
			fmt.Printf("built at: %s\n", date)
		},
	}

	// initCmd creates a default .respec.yaml file.
	var initCmd = &cobra.Command{
		Use:   "init",
		Short: "Create a default .respec.yaml configuration file",
		Long:  "Creates a default .respec.yaml file in the current directory. This file contains examples and documentation for all configuration options.",
		Run: func(cmd *cobra.Command, args []string) {
			configFileName := ".respec.yaml"
			if _, err := os.Stat(configFileName); err == nil {
				fmt.Fprintf(os.Stderr, "Error: '%s' already exists in the current directory. Aborting.\n", configFileName)
				os.Exit(1)
			}

			err := os.WriteFile(configFileName, []byte(defaultRespecYAML), 0644)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", configFileName, err)
				os.Exit(1)
			}
			fmt.Printf("✅ Successfully created '%s'.\n", configFileName)
		},
	}

	// validateCmd validates an OpenAPI specification file.
	var validateCmd = &cobra.Command{
		Use:   "validate <file>",
		Short: "Validate an OpenAPI specification file",
		Long:  "Validates that the given OpenAPI specification file (JSON or YAML) conforms to the OpenAPI 3.1 standard.",
		Args:  cobra.ExactArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			specPath := args[0]
			fmt.Printf("Validating specification at: %s\n", specPath)

			loader := openapi3.NewLoader()
			doc, err := loader.LoadFromFile(specPath)
			if err != nil {
				fmt.Fprintf(os.Stderr, "❌ Error loading specification file: %v\n", err)
				os.Exit(1)
			}

			err = doc.Validate(loader.Context)
			if err != nil {
				fmt.Fprintf(os.Stderr, "❌ Specification is invalid:\n%v\n", err)
				os.Exit(1)
			}

			fmt.Println("✅ Specification is valid.")
		},
	}

	// Register all commands and flags.
	rootCmd.AddCommand(versionCmd)
	rootCmd.AddCommand(initCmd)
	rootCmd.AddCommand(validateCmd)
	rootCmd.Flags().StringVarP(&outputPath, "output", "o", "openapi.yaml", "Output file for the OpenAPI specification (e.g., openapi.yaml or openapi.json)")

	// Execute the root command.
	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}
